name: Check version of the dependencies
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-updates:
    name: Check for updates
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update && sudo apt install -y python3 curl jq sed gawk wget gnupg software-properties-common

      - name: Update Dockerfile
        run: sh ./ci/versions_checker.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'chore: update dependencies'
          delete-branch: true
          title: 'chore: update dependencies'
          branch: chore/update-dependencies
          reviewers: |
            Darkness4
